AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  strapi-gateway

  SAM Template for strapi-gateway
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  StrapiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: strapi/
      Handler: app.lambdaHandler
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:eu-west-3:867511985106:secret:prenda-sOTFBx'
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Strapi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /activity
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
        External:
        - "@aws-sdk/client-secrets-manager"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StrapiApi:
    Description: "API Gateway endpoint URL for Prod stage for Strapi gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/strapi/"
  StrapiFunction:
    Description: "Strapi gateway Lambda Function ARN"
    Value: !GetAtt StrapiFunction.Arn
  StrapiFunctionIamRole:
    Description: "Implicit IAM Role created for Strapi gateway function"
    Value: !GetAtt StrapiFunctionRole.Arn
